/**
 * Type patches for ash_rpc.ts
 * These types should be generated by the backend but are currently missing
 */

export type SignInTenantMetadata = {
  token: string;
};

export type SuperAdminSignInMetadata = {
  token: string;
};

export type RegisterInTenantMetadata = {
  token: string;
};

export type RegisterSuperAdminMetadata = {
  token: string;
};
