import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :kg_edu, KgEduWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json", static_paths: ["static", "uploads"]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :waffle,
  storage: Waffle.Storage.AliyunOss,
  bucket: "kg-edu",
  region: "cn-beijing",
  endpoint: "oss-cn-beijing.aliyuncs.com",
  access_key_id: "LTAI5tA3M63FNf9qJPGwHGMU",
  access_key_secret: "Y481c9cjNvloxWTC0WOkLw8qWM9FMI"


config :kg_edu, KgEduWeb.Endpoint,
  url: [host: "localhost", port: 4000],
  static_url: [path: "/"],
  static: [
    at: "/",
    from: :my_app,
    gzip: false,
    only: ~w(js css images fonts favicon.ico robots.txt index.html)
  ]
