defmodule KgEdu.Repo.Migrations.UpdateKnowledge do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_resources) do
      remove :knowlege_type
      modify :unit, :text, null: true
      modify :subject, :text, null: true
      add :knowledge_type, :text, null: false, default: "knowledge_cell"
      add :importance_level, :text, null: false, default: "normal"

      add :parent_subject_id,
          references(:knowledge_resources,
            column: :id,
            name: "knowledge_resources_parent_subject_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :parent_unit_id,
          references(:knowledge_resources,
            column: :id,
            name: "knowledge_resources_parent_unit_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:knowledge_resources, "knowledge_resources_parent_subject_id_fkey")

    drop constraint(:knowledge_resources, "knowledge_resources_parent_unit_id_fkey")

    alter table(:knowledge_resources) do
      remove :parent_unit_id
      remove :parent_subject_id
      remove :importance_level
      remove :knowledge_type
      modify :subject, :text, null: false
      modify :unit, :text, null: false
      add :knowlege_type, :text, null: false, default: "normal"
    end
  end
end
