defmodule KgEdu.Repo.Migrations.AddCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_enrollments) do
      remove :student_id

      modify :member_id,
             references(:users,
               column: :id,
               name: "course_enrollments_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:course_enrollments, [:member_id])
  end

  def down do
    drop_if_exists index(:course_enrollments, [:member_id])

    drop constraint(:course_enrollments, "course_enrollments_member_id_fkey")

    alter table(:course_enrollments) do
      modify :member_id, :uuid

      add :student_id,
          references(:users,
            column: :id,
            name: "course_enrollments_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
