defmodule KgEdu.Repo.Migrations.AddAiTypeToExercises do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  

  def up do
    alter table(:exercises) do
      add :ai_type, :text
    end
  end

  def down do
    alter table(:exercises) do
      remove :ai_type
    end
  end
end
