defmodule KgEdu.Repo.Migrations.AddCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses) do
      add :publish_status, :boolean, default: true
    end
  end

  def down do
    alter table(:courses) do
      remove :publish_status
    end
  end
end
