defmodule KgEdu.Repo.Migrations.AddMajorSemesterFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses) do
      add :major, :text
      add :semester, :text
    end
  end

  def down do
    alter table(:courses) do
      remove :semester
      remove :major
    end
  end
end
