defmodule KgEdu.Repo.Migrations.UpdateResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_resources) do
      modify :importance_level, :text, default: ""
    end
  end

  def down do
    alter table(:knowledge_resources) do
      modify :importance_level, :text, default: "normal"
    end
  end
end
