defmodule KgEdu.Repo.Migrations.AddExercise do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:exercises, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :question_content, :text, null: false
      add :answer, :text, null: false
      add :question_type, :text, null: false
      add :options, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "exercises_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :course_id,
          references(:courses,
            column: :id,
            name: "exercises_course_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "exercises_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:exercises, [:title, :course_id],
             name: "exercises_unique_title_per_course_index"
           )
  end

  def down do
    drop_if_exists unique_index(:exercises, [:title, :course_id],
                     name: "exercises_unique_title_per_course_index"
                   )

    drop constraint(:exercises, "exercises_knowledge_resource_id_fkey")

    drop constraint(:exercises, "exercises_course_id_fkey")

    drop constraint(:exercises, "exercises_created_by_id_fkey")

    drop table(:exercises)
  end
end
