defmodule KgEdu.Repo.Migrations.UpdateKnowledgeResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_resources) do
      add :course_id,
          references(:courses,
            column: :id,
            name: "knowledge_resources_course_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists unique_index(:knowledge_resources, [:name],
                     name: "knowledge_resources_unique_name_index"
                   )

    create unique_index(:knowledge_resources, [:name, :course_id],
             name: "knowledge_resources_unique_name_per_course_index"
           )
  end

  def down do
    drop_if_exists unique_index(:knowledge_resources, [:name, :course_id],
                     name: "knowledge_resources_unique_name_per_course_index"
                   )

    create unique_index(:knowledge_resources, [:name],
             name: "knowledge_resources_unique_name_index"
           )

    drop constraint(:knowledge_resources, "knowledge_resources_course_id_fkey")

    alter table(:knowledge_resources) do
      remove :course_id
    end
  end
end
