defmodule KgEdu.Repo.Migrations.ExercisesUniqueTitlePerCourse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :phone, :text
    end

    drop_if_exists unique_index(:exercises, [:title, :course_id],
                     name: "exercises_unique_title_per_course_index"
                   )
  end

  def down do
    create unique_index(:exercises, [:title, :course_id],
             name: "exercises_unique_title_per_course_index"
           )

    alter table(:users) do
      remove :phone
    end
  end
end
