defmodule KgEdu.Repo.Migrations.ImageUrl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files) do
      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "files_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:files, "files_knowledge_resource_id_fkey")

    alter table(:files) do
      remove :knowledge_resource_id
    end
  end
end
