defmodule KgEdu.Repo.Migrations.DeleteAllExercises do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:exercises, "exercises_knowledge_resource_id_fkey")

    alter table(:exercises) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "exercises_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:exercises, "exercises_knowledge_resource_id_fkey")

    alter table(:exercises) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "exercises_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
