defmodule KgEdu.Repo.Migrations.ModifyKnowledge do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_resources) do
      add :subject, :text, null: false
      add :unit, :text, null: false
      add :knowlege_type, :text, null: false, default: "normal"
    end
  end

  def down do
    alter table(:knowledge_resources) do
      remove :knowlege_type
      remove :unit
      remove :subject
    end
  end
end
