defmodule KgEdu.Repo.Migrations.CourseInfoRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_infos) do
      remove :course_benefits
      remove :target_students
      remove :teacher_avatar
      remove :teacher_bio
      remove :teacher_name
      remove :status
      remove :recommended_grade_level
      remove :recommended_grade
      remove :duration_type
      remove :total_duration
      remove :start_time
      remove :course_type
      remove :name

      add :course_id,
          references(:courses,
            column: :id,
            name: "course_infos_course_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :background, :text, null: false
      add :target, :text
      add :course_structure, :text
    end
  end

  def down do
    drop constraint(:course_infos, "course_infos_course_id_fkey")

    alter table(:course_infos) do
      remove :course_structure
      remove :target
      remove :background
      remove :course_id
      add :name, :text, null: false
      add :course_type, :text
      add :start_time, :utc_datetime
      add :total_duration, :bigint
      add :duration_type, :text
      add :recommended_grade, :text
      add :recommended_grade_level, :text
      add :status, :text, default: "draft"
      add :teacher_name, :text
      add :teacher_bio, :text
      add :teacher_avatar, :text
      add :target_students, :text
      add :course_benefits, :text
    end
  end
end
