defmodule KgEdu.Repo.Migrations.RemoveName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:relation_types) do
      remove :is_symmetric
      remove :inverse_name
    end
  end

  def down do
    alter table(:relation_types) do
      add :inverse_name, :text
      add :is_symmetric, :boolean, null: false, default: false
    end
  end
end
