defmodule KgEdu.Repo.Migrations.AddAssitant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_commands, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user, :text
      add :system, :text
      add :assistant, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ai_commands, [:user, :system, :assistant],
             name: "ai_commands_unique_user_system_assistant_trio_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ai_commands, [:user, :system, :assistant],
                     name: "ai_commands_unique_user_system_assistant_trio_index"
                   )

    drop table(:ai_commands)
  end
end
