defmodule KgEdu.Repo.Migrations.AddVideo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files) do
      add :asset_id, :text
      add :playback_id, :text
    end
  end

  def down do
    alter table(:files) do
      remove :playback_id
      remove :asset_id
    end
  end
end
