defmodule KgEdu.Repo.Migrations.AddCodeToCourseID do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # First add the column as nullable to handle existing records
    alter table(:books) do
      add :course_id,
          references(:courses,
            column: :id,
            name: "books_course_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: true
    end

    # For now, we'll keep it nullable. The application layer will enforce the constraint
    # You can add a separate migration later to clean up data and make it NOT NULL
    
    create unique_index(:books, [:course_id], name: "books_unique_course_book_index")
  end

  def down do
    drop_if_exists unique_index(:books, [:course_id], name: "books_unique_course_book_index")

    drop constraint(:books, "books_course_id_fkey")

    alter table(:books) do
      remove :course_id
    end
  end
end
