defmodule KgEdu.Repo.Migrations.Homework do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:homeworks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :content, :text, null: false
      add :score, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "homeworks_course_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :chapter_id,
          references(:chapters,
            column: :id,
            name: "homeworks_chapter_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "homeworks_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_by_id,
          references(:users,
            column: :id,
            name: "homeworks_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:homeworks, "homeworks_course_id_fkey")

    drop constraint(:homeworks, "homeworks_chapter_id_fkey")

    drop constraint(:homeworks, "homeworks_knowledge_resource_id_fkey")

    drop constraint(:homeworks, "homeworks_created_by_id_fkey")

    drop table(:homeworks)
  end
end
