defmodule KgEdu.Repo.Migrations.Rename do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:users, [:student_id], name: "users_unique_student_id_index")

    rename table(:users), :student_id, to: :member_id

    create unique_index(:users, [:member_id], name: "users_unique_member_id_index")

    alter table(:course_enrollments) do
      add :member_id, :uuid, null: false
    end

    drop_if_exists unique_index(:course_enrollments, [:course_id, :student_id],
                     name: "course_enrollments_unique_course_student_index"
                   )

    create unique_index(:course_enrollments, [:course_id, :member_id],
             name: "course_enrollments_unique_course_student_index"
           )
  end

  def down do
    drop_if_exists unique_index(:course_enrollments, [:course_id, :member_id],
                     name: "course_enrollments_unique_course_student_index"
                   )

    create unique_index(:course_enrollments, [:course_id, :student_id],
             name: "course_enrollments_unique_course_student_index"
           )

    alter table(:course_enrollments) do
      remove :member_id
    end

    drop_if_exists unique_index(:users, [:member_id], name: "users_unique_member_id_index")

    rename table(:users), :member_id, to: :student_id

    create unique_index(:users, [:student_id], name: "users_unique_student_id_index")
  end
end
