defmodule KgEdu.Repo.Migrations.RemoveUniqueName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:knowledge_resources, [:name, :course_id],
                     name: "knowledge_resources_unique_name_per_course_index"
                   )
  end

  def down do
    create unique_index(:knowledge_resources, [:name, :course_id],
             name: "knowledge_resources_unique_name_per_course_index"
           )
  end
end
