defmodule KgEdu.Repo.Migrations.AddVideoThumbnail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      add :thumbnail, :text
    end
  end

  def down do
    alter table(:videos) do
      remove :thumbnail
    end
  end
end
