defmodule KgEdu.Repo.Migrations.CreateActivityLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:activity_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "activity_logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :action_type, :text, null: false
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    # Add indexes for better performance
    create index(:activity_logs, [:user_id, :inserted_at])
    create index(:activity_logs, [:action_type, :inserted_at])
    create index(:activity_logs, [:resource_type, :resource_id])
    create index(:activity_logs, [:user_id, :action_type, :inserted_at])
  end

  def down do
    drop constraint(:activity_logs, "activity_logs_user_id_fkey")

    drop table(:activity_logs)
  end
end
