defmodule KgEdu.Repo.Migrations.AddBookToCourse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses) do
      add :book_id,
          references(:books,
            column: :id,
            name: "courses_book_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:courses, "courses_book_id_fkey")

    alter table(:courses) do
      remove :book_id
    end
  end
end
