defmodule KgEdu.Repo.Migrations.FixUplaod do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      modify :playback_id, :text, null: false
      modify :asset_id, :text, null: false
    end
  end

  def down do
    alter table(:videos) do
      modify :asset_id, :text, null: true
      modify :playback_id, :text, null: true
    end
  end
end
