defmodule KgEdu.Repo.Migrations.AddStudent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :class_name, :text
      add :major, :text
      add :colledge, :text
    end
  end

  def down do
    alter table(:users) do
      remove :colledge
      remove :major
      remove :class_name
    end
  end
end
