defmodule KgEdu.Repo.Migrations.CourseInfoMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:course_infos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :course_type, :text
      add :start_time, :utc_datetime
      add :total_duration, :bigint
      add :duration_type, :text
      add :recommended_grade, :text
      add :recommended_grade_level, :text
      add :status, :text, default: "draft"
      add :teacher_name, :text
      add :teacher_bio, :text
      add :teacher_avatar, :text
      add :objectives, :text
      add :target_students, :text
      add :course_highlights, :text
      add :course_introduction, :text
      add :course_benefits, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:course_infos)
  end
end
