defmodule KgEdu.Repo.Migrations.AddAnswer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:homeworks) do
      add :answer, :text
    end
  end

  def down do
    alter table(:homeworks) do
      remove :answer
    end
  end
end
