defmodule KgEdu.Repo.Migrations.AddCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Add course_id column if it doesn't exist
    try do
      execute("ALTER TABLE books ADD COLUMN IF NOT EXISTS course_id UUID")
    rescue
      Postgrex.Error -> 
        # Column might already exist, ignore error
        :ok
    end
  end

  def down do
    # Remove column if it exists
    execute("ALTER TABLE books DROP COLUMN IF EXISTS course_id")
  end
end
