defmodule KgEdu.Repo.Migrations.AddStudentIdToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # First add the column as nullable
    alter table(:users) do
      add :student_id, :text, null: true
    end

    # Update existing records to have a temporary student_id based on email
    execute """
    UPDATE users 
    SET student_id = 'temp_' || REPLACE(email, '@', '_') 
    WHERE student_id IS NULL
    """, """
    UPDATE users 
    SET student_id = NULL 
    WHERE student_id LIKE 'temp_%'
    """

    # Drop the old unique constraint
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    # Make student_id not nullable and email nullable
    alter table(:users) do
      modify :student_id, :text, null: false
      modify :email, :citext, null: true
    end

    # Create new unique constraint
    create unique_index(:users, [:student_id], name: "users_unique_student_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:student_id], name: "users_unique_student_id_index")

    alter table(:users) do
      modify :email, :citext, null: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :student_id
    end
  end
end
