defmodule KgEdu.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:chapters, "chapters_parent_chapter_id_fkey")

    alter table(:chapters) do
      modify :parent_chapter_id,
             references(:chapters,
               column: :id,
               name: "chapters_parent_chapter_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:chapters, "chapters_parent_chapter_id_fkey")

    alter table(:chapters) do
      modify :parent_chapter_id,
             references(:chapters,
               column: :id,
               name: "chapters_parent_chapter_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
