defmodule KgEdu.Repo.Migrations.UpdateCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:videos, "videos_chapter_id_fkey")

    alter table(:videos) do
      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "videos_chapter_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:knowledge_resources, "knowledge_resources_chapter_id_fkey")

    alter table(:knowledge_resources) do
      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "knowledge_resources_chapter_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:homeworks, "homeworks_chapter_id_fkey")

    alter table(:homeworks) do
      modify :created_by_id, :uuid, null: true

      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "homeworks_chapter_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:chapters, "chapters_parent_chapter_id_fkey")

    alter table(:chapters) do
      modify :parent_chapter_id,
             references(:chapters,
               column: :id,
               name: "chapters_parent_chapter_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:chapters, "chapters_parent_chapter_id_fkey")

    alter table(:chapters) do
      modify :parent_chapter_id,
             references(:chapters,
               column: :id,
               name: "chapters_parent_chapter_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:homeworks, "homeworks_chapter_id_fkey")

    alter table(:homeworks) do
      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "homeworks_chapter_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :created_by_id, :uuid, null: false
    end

    drop constraint(:knowledge_resources, "knowledge_resources_chapter_id_fkey")

    alter table(:knowledge_resources) do
      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "knowledge_resources_chapter_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:videos, "videos_chapter_id_fkey")

    alter table(:videos) do
      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "videos_chapter_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
