defmodule KgEdu.Repo.Migrations.AddVideoDuration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      add :duration, :bigint
    end
  end

  def down do
    alter table(:videos) do
      remove :duration
    end
  end
end
