defmodule KgEdu.Repo.Migrations.UpdateExercise do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:exercises) do
      modify :course_id, :uuid, null: true
    end
  end

  def down do
    alter table(:exercises) do
      modify :course_id, :uuid, null: false
    end
  end
end
