defmodule KgEdu.Repo.Migrations.ChangeDuration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      modify :duration, :float
    end
  end

  def down do
    alter table(:videos) do
      modify :duration, :bigint
    end
  end
end
