defmodule KgEdu.Repo.Migrations.AddAccountsOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:knowledge_resources, "knowledge_resources_created_by_id_fkey")

    alter table(:knowledge_resources) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "knowledge_resources_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:knowledge_relations, "knowledge_relations_created_by_id_fkey")

    alter table(:knowledge_relations) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "knowledge_relations_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:knowledge_questions, "knowledge_questions_created_by_id_fkey")

    alter table(:knowledge_questions) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "knowledge_questions_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:homeworks, "homeworks_created_by_id_fkey")

    alter table(:homeworks) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "homeworks_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:exercises, "exercises_created_by_id_fkey")

    alter table(:exercises) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "exercises_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:courses, "courses_teacher_id_fkey")

    alter table(:courses) do
      modify :teacher_id,
             references(:users,
               column: :id,
               name: "courses_teacher_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:course_enrollments, "course_enrollments_member_id_fkey")

    alter table(:course_enrollments) do
      modify :member_id,
             references(:users,
               column: :id,
               name: "course_enrollments_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:activity_logs, "activity_logs_user_id_fkey")

    alter table(:activity_logs) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "activity_logs_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:activity_logs, "activity_logs_user_id_fkey")

    alter table(:activity_logs) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "activity_logs_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:course_enrollments, "course_enrollments_member_id_fkey")

    alter table(:course_enrollments) do
      modify :member_id,
             references(:users,
               column: :id,
               name: "course_enrollments_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:courses, "courses_teacher_id_fkey")

    alter table(:courses) do
      modify :teacher_id,
             references(:users,
               column: :id,
               name: "courses_teacher_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:exercises, "exercises_created_by_id_fkey")

    alter table(:exercises) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "exercises_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:homeworks, "homeworks_created_by_id_fkey")

    alter table(:homeworks) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "homeworks_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:knowledge_questions, "knowledge_questions_created_by_id_fkey")

    alter table(:knowledge_questions) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "knowledge_questions_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:knowledge_relations, "knowledge_relations_created_by_id_fkey")

    alter table(:knowledge_relations) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "knowledge_relations_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:knowledge_resources, "knowledge_resources_created_by_id_fkey")

    alter table(:knowledge_resources) do
      modify :created_by_id,
             references(:users,
               column: :id,
               name: "knowledge_resources_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
