defmodule KgEdu.Repo.Migrations.AddAttachment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:books) do
      add :attachment, :text
    end
  end

  def down do
    alter table(:books) do
      remove :attachment
    end
  end
end
