defmodule KgEdu.Repo.Migrations.RemoveUniqueCourseBookConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:books, [:course_id], name: "books_unique_course_book_index")
  end

  def down do
    create unique_index(:books, [:course_id], name: "books_unique_course_book_index")
  end
end
