defmodule KgEdu.Repo.Migrations.RemoveStyleConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_questions) do
      remove :style_config
    end

    alter table(:knowledge_question_connections) do
      remove :style_config
    end
  end

  def down do
    alter table(:knowledge_question_connections) do
      add :style_config, :map
    end

    alter table(:knowledge_questions) do
      add :style_config, :map
    end
  end
end
