defmodule KgEdu.Repo.Migrations.AddCreatedByIdToAiCommands do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_commands) do
      add :created_by_id, :uuid
    end

    drop_if_exists unique_index(:ai_commands, [:user, :system, :assistant],
                     name: "ai_commands_unique_user_system_assistant_trio_index"
                   )

    create unique_index(:ai_commands, [:user, :system, :assistant, :created_by_id],
             name: "ai_commands_unique_user_system_assistant_trio_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ai_commands, [:user, :system, :assistant, :created_by_id],
                     name: "ai_commands_unique_user_system_assistant_trio_index"
                   )

    create unique_index(:ai_commands, [:user, :system, :assistant],
             name: "ai_commands_unique_user_system_assistant_trio_index"
           )

    alter table(:ai_commands) do
      remove :created_by_id
    end
  end
end
