defmodule KgEdu.Repo.Migrations.AddTeacherEditPermission do
  @moduledoc """
  Adds teacher edit permission fields to users table (base repo).

  This file was autogenerated with `mix ash_postgres.generate_migrations`.
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :edit_enabled, :boolean, default: true
      add :edit_period_start, :date
      add :edit_period_end, :date
    end
  end

  def down do
    alter table(:users) do
      remove :edit_period_end
      remove :edit_period_start
      remove :edit_enabled
    end
  end
end
