defmodule KgEdu.Repo.Migrations.AddAiConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :thread_id, :text, null: false
      add :ai_command_id, :uuid
      add :created_by_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ai_conversations, [:thread_id],
             name: "ai_conversations_unique_thread_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ai_conversations, [:thread_id],
                     name: "ai_conversations_unique_thread_id_index"
                   )

    drop table(:ai_conversations)
  end
end
