defmodule KgEdu.Repo.TenantMigrations.AddData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: prefix()) do
      add :avatar_url, :text
    end

    alter table(:courses, prefix: prefix()) do
      add :semester_hours, :bigint
    end
  end

  def down do
    alter table(:courses, prefix: prefix()) do
      remove :semester_hours
    end

    alter table(:users, prefix: prefix()) do
      remove :avatar_url
    end
  end
end
