defmodule KgEdu.Repo.TenantMigrations.AddCreatedByToQuestionConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_question_connections, prefix: prefix()) do
      add :created_by_id,
          references(:users,
            column: :id,
            name: "knowledge_question_connections_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(
           :knowledge_question_connections,
           "knowledge_question_connections_created_by_id_fkey"
         )

    alter table(:knowledge_question_connections, prefix: prefix()) do
      remove :created_by_id
    end
  end
end
