defmodule KgEdu.Repo.TenantMigrations.AddCreatedByToFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files, prefix: prefix()) do
      add :created_by_id,
          references(:users,
            column: :id,
            name: "files_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:files, "files_created_by_id_fkey")

    alter table(:files, prefix: prefix()) do
      remove :created_by_id
    end
  end
end
