defmodule KgEdu.Repo.TenantMigrations.AddCreditsToCourses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses, prefix: prefix()) do
      add :credits, :bigint
    end
  end

  def down do
    alter table(:courses, prefix: prefix()) do
      remove :credits
    end
  end
end
