defmodule KgEdu.Repo.TenantMigrations.AddTenant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_assignments, prefix: prefix()) do
      modify :assigned_at, :utc_datetime, null: true
    end

    drop_if_exists unique_index(:course_assignments, [:course_id, :teacher_id],
                     name: "course_assignments_unique_course_teacher_index"
                   )
  end

  def down do
    create unique_index(:course_assignments, [:course_id, :teacher_id],
             name: "course_assignments_unique_course_teacher_index"
           )

    alter table(:course_assignments, prefix: prefix()) do
      modify :assigned_at, :utc_datetime, null: false
    end
  end
end
