defmodule KgEdu.Repo.TenantMigrations.AddSubjectCateegory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses, prefix: prefix()) do
      add :subject_category, :text
    end
  end

  def down do
    alter table(:courses, prefix: prefix()) do
      remove :subject_category
    end
  end
end
