defmodule KgEdu.Repo.TenantMigrations.AddLinkToKnowledge do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:links, prefix: prefix()) do
      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "links_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:links, "links_knowledge_resource_id_fkey")

    alter table(:links, prefix: prefix()) do
      remove :knowledge_resource_id
    end
  end
end
