defmodule KgEdu.Repo.TenantMigrations.AddTenantSupport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:videos, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :upload_id, :text
      add :asset_id, :text, null: false
      add :playback_id, :text, null: false
      add :duration, :float
      add :thumbnail, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :chapter_id, :uuid
      add :knowledge_resource_id, :uuid
    end

    create table(:tokens, primary_key: false, prefix: prefix()) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:relation_types, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :display_name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:relation_types, [:name], name: "relation_types_unique_name_index")

    create table(:links, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :url, :text, null: false
      add :category, :text
      add :course_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:knowledge_resources, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :knowledge_type, :text, null: false, default: "knowledge_cell"
      add :subject, :text
      add :unit, :text
      add :importance_level, :text, null: false, default: ""
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id, :uuid, null: false
      add :chapter_id, :uuid
      add :created_by_id, :uuid
      add :parent_subject_id, :uuid
      add :parent_unit_id, :uuid
    end

    create table(:knowledge_relations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :relation_type_id,
          references(:relation_types,
            column: :id,
            name: "knowledge_relations_relation_type_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :source_knowledge_id,
          references(:knowledge_resources,
            column: :id,
            name: "knowledge_relations_source_knowledge_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :target_knowledge_id,
          references(:knowledge_resources,
            column: :id,
            name: "knowledge_relations_target_knowledge_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "knowledge_relations_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create unique_index(
             :knowledge_relations,
             [:source_knowledge_id, :target_knowledge_id, :relation_type_id],
             name: "knowledge_relations_unique_relation_index"
           )

    create table(:knowledge_questions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :question_level, :text, null: false
      add :position, :bigint, null: false, default: 0
      add :tags, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id, :uuid, null: false
      add :created_by_id, :uuid
      add :knowledge_resource_id, :uuid
    end

    create table(:knowledge_question_connections, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :connection_type, :text, default: "hierarchy"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id, :uuid, null: false
      add :source_question_id, :uuid, null: false
      add :target_question_id, :uuid, null: false
    end

    create table(:homeworks, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :content, :text, null: false
      add :score, :decimal
      add :answer, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id, :uuid, null: false
      add :chapter_id, :uuid
      add :knowledge_resource_id, :uuid
      add :created_by_id, :uuid
    end

    create table(:files, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :asset_id, :text
      add :playback_id, :text
      add :path, :text, null: false
      add :size, :bigint, null: false
      add :file_type, :text, null: false
      add :purpose, :text, null: false, default: "course_file"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id, :uuid
      add :knowledge_resource_id, :uuid
    end

    create table(:exercises, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :question_content, :text, null: false
      add :answer, :text, null: false
      add :question_type, :text, null: false
      add :options, :map
      add :ai_type, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "exercises_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )

      add :course_id, :uuid
      add :created_by_id, :uuid
    end

    create table(:courses, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:links, prefix: prefix()) do
      modify :course_id,
             references(:courses,
               column: :id,
               name: "links_course_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:knowledge_resources, prefix: prefix()) do
      modify :course_id,
             references(:courses,
               column: :id,
               name: "knowledge_resources_course_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:knowledge_questions, prefix: prefix()) do
      modify :course_id,
             references(:courses,
               column: :id,
               name: "knowledge_questions_course_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "knowledge_questions_created_by_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_questions_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(:knowledge_questions, [:title, :question_level, :course_id],
             name: "knowledge_questions_unique_title_position_per_level_index"
           )

    alter table(:knowledge_question_connections, prefix: prefix()) do
      modify :course_id,
             references(:courses,
               column: :id,
               name: "knowledge_question_connections_course_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :source_question_id,
             references(:knowledge_questions,
               column: :id,
               name: "knowledge_question_connections_source_question_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :target_question_id,
             references(:knowledge_questions,
               column: :id,
               name: "knowledge_question_connections_target_question_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(
             :knowledge_question_connections,
             [:source_question_id, :target_question_id],
             name: "knowledge_question_connections_unique_connection_index"
           )

    alter table(:homeworks, prefix: prefix()) do
      modify :course_id,
             references(:courses,
               column: :id,
               name: "homeworks_course_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:files, prefix: prefix()) do
      modify :course_id,
             references(:courses,
               column: :id,
               name: "files_course_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "files_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:exercises, prefix: prefix()) do
      modify :course_id,
             references(:courses,
               column: :id,
               name: "exercises_course_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "exercises_created_by_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:courses, prefix: prefix()) do
      add :title, :text, null: false
      add :description, :text
      add :image_url, :text

      add :teacher_id,
          references(:users,
            column: :id,
            name: "courses_teacher_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :major, :text
      add :semester, :text
      add :book_id, :uuid
      add :publish_status, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:course_infos, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :course_id,
          references(:courses,
            column: :id,
            name: "course_infos_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :background, :text, null: false
      add :objectives, :text
      add :target, :text
      add :course_highlights, :text
      add :course_introduction, :text
      add :course_structure, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:course_enrollments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :course_id,
          references(:courses,
            column: :id,
            name: "course_enrollments_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :member_id,
          references(:users,
            column: :id,
            name: "course_enrollments_member_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :enrolled_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:course_enrollments, [:course_id, :member_id],
             name: "course_enrollments_unique_course_student_index"
           )

    create table(:chapters, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:videos, prefix: prefix()) do
      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "videos_chapter_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "videos_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(:videos, [:asset_id], name: "videos_unique_asset_id_index")

    create unique_index(:videos, [:playback_id], name: "videos_unique_playback_id_index")

    create unique_index(:videos, [:upload_id], name: "videos_unique_upload_id_index")

    alter table(:knowledge_resources, prefix: prefix()) do
      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "knowledge_resources_chapter_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "knowledge_resources_created_by_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :parent_subject_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_resources_parent_subject_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :parent_unit_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_resources_parent_unit_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:homeworks, prefix: prefix()) do
      modify :chapter_id,
             references(:chapters,
               column: :id,
               name: "homeworks_chapter_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "homeworks_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "homeworks_created_by_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:chapters, prefix: prefix()) do
      add :title, :text, null: false
      add :description, :text
      add :sort_order, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "chapters_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :parent_chapter_id,
          references(:chapters,
            column: :id,
            name: "chapters_parent_chapter_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )
    end

    create unique_index(:chapters, [:title, :course_id, :parent_chapter_id],
             name: "chapters_unique_title_per_course_parent_index"
           )

    create table(:books, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:courses, prefix: prefix()) do
      modify :book_id,
             references(:books,
               column: :id,
               name: "courses_book_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:books, prefix: prefix()) do
      add :title, :text, null: false
      add :publish, :boolean, null: false, default: false
      add :cover_image, :text
      add :attachment, :text

      add :course_id,
          references(:courses,
            column: :id,
            name: "books_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:activity_logs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "activity_logs_user_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :action_type, :text, null: false
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:activity_logs, "activity_logs_user_id_fkey")

    drop table(:activity_logs, prefix: prefix())

    drop constraint(:books, "books_course_id_fkey")

    alter table(:books, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :course_id
      remove :attachment
      remove :cover_image
      remove :publish
      remove :title
    end

    drop constraint(:courses, "courses_book_id_fkey")

    alter table(:courses, prefix: prefix()) do
      modify :book_id, :uuid
    end

    drop table(:books, prefix: prefix())

    drop_if_exists unique_index(:chapters, [:title, :course_id, :parent_chapter_id],
                     name: "chapters_unique_title_per_course_parent_index"
                   )

    drop constraint(:chapters, "chapters_course_id_fkey")

    drop constraint(:chapters, "chapters_parent_chapter_id_fkey")

    alter table(:chapters, prefix: prefix()) do
      remove :parent_chapter_id
      remove :course_id
      remove :updated_at
      remove :inserted_at
      remove :sort_order
      remove :description
      remove :title
    end

    drop constraint(:homeworks, "homeworks_chapter_id_fkey")

    drop constraint(:homeworks, "homeworks_knowledge_resource_id_fkey")

    drop constraint(:homeworks, "homeworks_created_by_id_fkey")

    alter table(:homeworks, prefix: prefix()) do
      modify :created_by_id, :uuid
      modify :knowledge_resource_id, :uuid
      modify :chapter_id, :uuid
    end

    drop constraint(:knowledge_resources, "knowledge_resources_chapter_id_fkey")

    drop constraint(:knowledge_resources, "knowledge_resources_created_by_id_fkey")

    drop constraint(:knowledge_resources, "knowledge_resources_parent_subject_id_fkey")

    drop constraint(:knowledge_resources, "knowledge_resources_parent_unit_id_fkey")

    alter table(:knowledge_resources, prefix: prefix()) do
      modify :parent_unit_id, :uuid
      modify :parent_subject_id, :uuid
      modify :created_by_id, :uuid
      modify :chapter_id, :uuid
    end

    drop_if_exists unique_index(:videos, [:upload_id], name: "videos_unique_upload_id_index")

    drop_if_exists unique_index(:videos, [:playback_id], name: "videos_unique_playback_id_index")

    drop_if_exists unique_index(:videos, [:asset_id], name: "videos_unique_asset_id_index")

    drop constraint(:videos, "videos_chapter_id_fkey")

    drop constraint(:videos, "videos_knowledge_resource_id_fkey")

    alter table(:videos, prefix: prefix()) do
      modify :knowledge_resource_id, :uuid
      modify :chapter_id, :uuid
    end

    drop table(:chapters, prefix: prefix())

    drop_if_exists unique_index(:course_enrollments, [:course_id, :member_id],
                     name: "course_enrollments_unique_course_student_index"
                   )

    drop constraint(:course_enrollments, "course_enrollments_course_id_fkey")

    drop constraint(:course_enrollments, "course_enrollments_member_id_fkey")

    drop table(:course_enrollments, prefix: prefix())

    drop constraint(:course_infos, "course_infos_course_id_fkey")

    drop table(:course_infos, prefix: prefix())

    drop constraint(:courses, "courses_teacher_id_fkey")

    alter table(:courses, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :publish_status
      remove :book_id
      remove :semester
      remove :major
      remove :teacher_id
      remove :image_url
      remove :description
      remove :title
    end

    drop constraint(:exercises, "exercises_course_id_fkey")

    drop constraint(:exercises, "exercises_created_by_id_fkey")

    alter table(:exercises, prefix: prefix()) do
      modify :created_by_id, :uuid
      modify :course_id, :uuid
    end

    drop constraint(:files, "files_course_id_fkey")

    drop constraint(:files, "files_knowledge_resource_id_fkey")

    alter table(:files, prefix: prefix()) do
      modify :knowledge_resource_id, :uuid
      modify :course_id, :uuid
    end

    drop constraint(:homeworks, "homeworks_course_id_fkey")

    alter table(:homeworks, prefix: prefix()) do
      modify :course_id, :uuid
    end

    drop_if_exists unique_index(
                     :knowledge_question_connections,
                     [:source_question_id, :target_question_id],
                     name: "knowledge_question_connections_unique_connection_index"
                   )

    drop constraint(
           :knowledge_question_connections,
           "knowledge_question_connections_course_id_fkey"
         )

    drop constraint(
           :knowledge_question_connections,
           "knowledge_question_connections_source_question_id_fkey"
         )

    drop constraint(
           :knowledge_question_connections,
           "knowledge_question_connections_target_question_id_fkey"
         )

    alter table(:knowledge_question_connections, prefix: prefix()) do
      modify :target_question_id, :uuid
      modify :source_question_id, :uuid
      modify :course_id, :uuid
    end

    drop_if_exists unique_index(:knowledge_questions, [:title, :question_level, :course_id],
                     name: "knowledge_questions_unique_title_position_per_level_index"
                   )

    drop constraint(:knowledge_questions, "knowledge_questions_course_id_fkey")

    drop constraint(:knowledge_questions, "knowledge_questions_created_by_id_fkey")

    drop constraint(:knowledge_questions, "knowledge_questions_knowledge_resource_id_fkey")

    alter table(:knowledge_questions, prefix: prefix()) do
      modify :knowledge_resource_id, :uuid
      modify :created_by_id, :uuid
      modify :course_id, :uuid
    end

    drop constraint(:knowledge_resources, "knowledge_resources_course_id_fkey")

    alter table(:knowledge_resources, prefix: prefix()) do
      modify :course_id, :uuid
    end

    drop constraint(:links, "links_course_id_fkey")

    alter table(:links, prefix: prefix()) do
      modify :course_id, :uuid
    end

    drop table(:courses, prefix: prefix())

    drop constraint(:exercises, "exercises_knowledge_resource_id_fkey")

    drop table(:exercises, prefix: prefix())

    drop table(:files, prefix: prefix())

    drop table(:homeworks, prefix: prefix())

    drop table(:knowledge_question_connections, prefix: prefix())

    drop table(:knowledge_questions, prefix: prefix())

    drop_if_exists unique_index(
                     :knowledge_relations,
                     [:source_knowledge_id, :target_knowledge_id, :relation_type_id],
                     name: "knowledge_relations_unique_relation_index"
                   )

    drop constraint(:knowledge_relations, "knowledge_relations_relation_type_id_fkey")

    drop constraint(:knowledge_relations, "knowledge_relations_source_knowledge_id_fkey")

    drop constraint(:knowledge_relations, "knowledge_relations_target_knowledge_id_fkey")

    drop constraint(:knowledge_relations, "knowledge_relations_created_by_id_fkey")

    drop table(:knowledge_relations, prefix: prefix())

    drop table(:knowledge_resources, prefix: prefix())

    drop table(:links, prefix: prefix())

    drop_if_exists unique_index(:relation_types, [:name],
                     name: "relation_types_unique_name_index"
                   )

    drop table(:relation_types, prefix: prefix())

    drop table(:tokens, prefix: prefix())

    drop table(:videos, prefix: prefix())
  end
end
