defmodule KgEdu.Repo.TenantMigrations.AddClass do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: prefix()) do
      add :class_id, :uuid
      add :job_title, :text
      add :bio, :text
    end

    create table(:classes, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users, prefix: prefix()) do
      modify :class_id,
             references(:classes,
               column: :id,
               name: "users_class_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:classes, prefix: prefix()) do
      add :name, :text, null: false
      add :college, :text
      add :major, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:classes, [:name, :college, :major],
             name: "classes_unique_class_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:classes, [:name, :college, :major],
                     name: "classes_unique_class_name_index"
                   )

    alter table(:classes, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :major
      remove :college
      remove :name
    end

    drop constraint(:users, "users_class_id_fkey")

    alter table(:users, prefix: prefix()) do
      modify :class_id, :uuid
    end

    drop table(:classes, prefix: prefix())

    alter table(:users, prefix: prefix()) do
      remove :bio
      remove :job_title
      remove :class_id
    end
  end
end
