defmodule KgEdu.Repo.TenantMigrations.AddCourseAssignment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses, prefix: prefix()) do
      remove :teacher_id
    end

    create table(:course_assignments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "assistant_teacher"

      add :assigned_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :assigned_by_id,
          references(:users,
            column: :id,
            name: "course_assignments_assigned_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "course_assignments_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :teacher_id,
          references(:users,
            column: :id,
            name: "course_assignments_teacher_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create unique_index(:course_assignments, [:course_id, :teacher_id],
             name: "course_assignments_unique_course_teacher_index"
           )
  end

  def down do
    drop_if_exists unique_index(:course_assignments, [:course_id, :teacher_id],
                     name: "course_assignments_unique_course_teacher_index"
                   )

    drop constraint(:course_assignments, "course_assignments_assigned_by_id_fkey")

    drop constraint(:course_assignments, "course_assignments_course_id_fkey")

    drop constraint(:course_assignments, "course_assignments_teacher_id_fkey")

    drop table(:course_assignments, prefix: prefix())

    alter table(:courses, prefix: prefix()) do
      add :teacher_id,
          references(:users,
            column: :id,
            name: "courses_teacher_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end
end
