defmodule KgEdu.Repo.TenantMigrations.AddKnowledgePointCognitiveResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_point_cognitives, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :cognitive_level, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :learning_outcome, :text
      add :difficulty, :text, default: "medium"
      add :estimated_time, :bigint
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "knowledge_point_cognitives_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "knowledge_point_cognitives_created_by_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(
           :knowledge_point_cognitives,
           "knowledge_point_cognitives_knowledge_resource_id_fkey"
         )

    drop constraint(:knowledge_point_cognitives, "knowledge_point_cognitives_created_by_id_fkey")

    drop table(:knowledge_point_cognitives, prefix: prefix())
  end
end
