defmodule KgEdu.Repo.TenantMigrations.AddAccountsOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :member_id, :text, null: false
      add :name, :text
      add :phone, :text
      add :class_name, :text
      add :major, :text
      add :colledge, :text
      add :email, :citext
      add :hashed_password, :text, null: false
      add :role, :text, null: false, default: "user"
    end

    create unique_index(:users, [:member_id], name: "users_unique_member_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:member_id], name: "users_unique_member_id_index")

    drop table(:users, prefix: prefix())
  end
end
