defmodule KgEdu.Repo.TenantMigrations.AddUserSchoolField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: prefix()) do
      add :school, :text
    end
  end

  def down do
    alter table(:users, prefix: prefix()) do
      remove :school
    end
  end
end
