defmodule KgEdu.Repo.TenantMigrations.AddAuthor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:books, prefix: prefix()) do
      add :author, :text
      add :publisher, :text
    end
  end

  def down do
    alter table(:books, prefix: prefix()) do
      remove :publisher
      remove :author
    end
  end
end
