defmodule KgEdu.Repo.TenantMigrations.AddSubjectCateegoryResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # First, create the subject_categories table
    create table(:subject_categories, prefix: prefix(), primary_key: false) do
      add :id, :uuid, primary_key: true, default: fragment("gen_random_uuid()")
      add :name, :string, null: false
      add :description, :string
      add :code, :string
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    # Create unique index on name
    create unique_index(:subject_categories, [:name], prefix: prefix())

    # Rename column and handle data type conversion
    rename table(:courses), :subject_category, to: :subject_category_id

    # Set all existing values to NULL since they're text and can't be cast to UUID
    execute "UPDATE #{prefix()}.courses SET subject_category_id = NULL", ""

    # Now change the column type to binary_id (UUID) with explicit casting
    execute "ALTER TABLE #{prefix()}.courses ALTER COLUMN subject_category_id TYPE UUID USING subject_category_id::uuid", ""

    # Add the foreign key constraint
    alter table(:courses, prefix: prefix()) do
      modify :subject_category_id,
             references(:subject_categories,
               column: :id,
               name: "courses_subject_category_id_fkey",
               type: :binary_id,
               prefix: prefix()
             )
    end
  end

  def down do
    drop constraint(:courses, "courses_subject_category_id_fkey")

    alter table(:courses, prefix: prefix()) do
      modify :subject_category_id, :text
    end

    rename table(:courses), :subject_category_id, to: :subject_category

    drop table(:subject_categories, prefix: prefix())
  end
end
