defmodule KgEdu.Repo.TenantMigrations.CheckDrift do
  @moduledoc """
  Fresh-install backfill (tenants).

  Originally autogenerated, but the email_messages.course_id column + FK it
  adds is already covered by 20260825000000_add_course_id_to_email_messages,
  whose change was never recorded in a snapshot. Kept as a no-op so the new
  snapshot (20260906135258) is recorded without breaking new or existing
  tenant schemas.
  """

  use Ecto.Migration

  def up, do: :ok
  def down, do: :ok
end
