defmodule KgEdu.Repo.TenantMigrations.AddCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # The index was already created with the short name during resource creation
    # This migration is no longer needed, so we do nothing
    :ok
  end

  def down do
    # Nothing to rollback since we didn't make changes
    :ok
  end
end
