defmodule KgEdu.Repo.TenantMigrations.AddGroupTaskAndMajorAnalysis do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:analysis_reports, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :report_type, :text, null: false
      add :content, :text
      add :ai_generated, :boolean, null: false, default: false
      add :generated_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :major_id, :uuid, null: false
    end

    create table(:group_members, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id, :uuid, null: false
      add :student_id, :uuid, null: false
    end

    create table(:curriculum_designs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :design_data, :text
      add :ai_generated, :boolean, null: false, default: false
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :major_id, :uuid, null: false
    end

    create table(:majors, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:analysis_reports, prefix: prefix()) do
      modify :major_id,
             references(:majors,
               column: :id,
               name: "analysis_reports_major_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    alter table(:curriculum_designs, prefix: prefix()) do
      modify :major_id,
             references(:majors,
               column: :id,
               name: "curriculum_designs_major_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    alter table(:majors, prefix: prefix()) do
      add :name, :text, null: false
      add :code, :text
      add :description, :text
      add :college, :text
      add :degree_type, :text
      add :duration, :bigint
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:major_competencies, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :category, :text, null: false, default: "professional"
      add :level, :text
      add :description, :text
      add :weight, :float, default: 1.0
      add :ai_generated, :boolean, null: false, default: false

      add :parent_id,
          references(:major_competencies,
            column: :id,
            name: "major_competencies_parent_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :major_id,
          references(:majors,
            column: :id,
            name: "major_competencies_major_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:groups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:group_members, prefix: prefix()) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_members_group_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :student_id,
             references(:users,
               column: :id,
               name: "group_members_student_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    create unique_index(:group_members, [:group_id, :student_id],
             name: "group_members_unique_group_student_index"
           )

    alter table(:groups, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text
      add :max_members, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "groups_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "groups_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:task_groups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id, :uuid, null: false
      add :group_id, :uuid, null: false
    end

    create table(:group_tasks, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:task_groups, prefix: prefix()) do
      modify :task_id,
             references(:group_tasks,
               column: :id,
               name: "task_groups_task_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :group_id,
             references(:groups,
               column: :id,
               name: "task_groups_group_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    create unique_index(:task_groups, [:task_id, :group_id],
             name: "task_groups_unique_task_group_index"
           )

    alter table(:group_tasks, prefix: prefix()) do
      add :title, :text, null: false
      add :description, :text
      add :task_type, :text, null: false, default: "submission"
      add :status, :text, null: false, default: "draft"
      add :token, :text
      add :due_date, :utc_datetime_usec
      add :publish_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "group_tasks_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "group_tasks_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:discussion_replies, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :discussion_id,
          references(:discussions,
            column: :id,
            name: "discussion_replies_discussion_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "discussion_replies_user_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :nilify_all
          )
    end

    create table(:task_submissions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text
      add :file_url, :text
      add :status, :text, null: false, default: "pending"
      add :score, :float
      add :feedback, :text
      add :submitted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:group_tasks,
            column: :id,
            name: "task_submissions_task_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "task_submissions_group_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :student_id,
          references(:users,
            column: :id,
            name: "task_submissions_student_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:courses, prefix: prefix()) do
      add :color_scheme, :text, default: "auto"
    end

    create table(:job_positions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :requirements, :text
      add :salary_range, :text
      add :source, :text
      add :ai_analysis, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :major_id,
          references(:majors,
            column: :id,
            name: "job_positions_major_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:job_positions, "job_positions_major_id_fkey")

    drop table(:job_positions, prefix: prefix())

    alter table(:courses, prefix: prefix()) do
      remove :color_scheme
    end

    drop constraint(:task_submissions, "task_submissions_task_id_fkey")

    drop constraint(:task_submissions, "task_submissions_group_id_fkey")

    drop constraint(:task_submissions, "task_submissions_student_id_fkey")

    drop table(:task_submissions, prefix: prefix())

    drop constraint(:discussion_replies, "discussion_replies_discussion_id_fkey")

    drop constraint(:discussion_replies, "discussion_replies_user_id_fkey")

    drop table(:discussion_replies, prefix: prefix())

    drop constraint(:group_tasks, "group_tasks_course_id_fkey")

    drop constraint(:group_tasks, "group_tasks_created_by_id_fkey")

    alter table(:group_tasks, prefix: prefix()) do
      remove :created_by_id
      remove :course_id
      remove :updated_at
      remove :inserted_at
      remove :publish_at
      remove :due_date
      remove :token
      remove :status
      remove :task_type
      remove :description
      remove :title
    end

    drop_if_exists unique_index(:task_groups, [:task_id, :group_id],
                     name: "task_groups_unique_task_group_index"
                   )

    drop constraint(:task_groups, "task_groups_task_id_fkey")

    drop constraint(:task_groups, "task_groups_group_id_fkey")

    alter table(:task_groups, prefix: prefix()) do
      modify :group_id, :uuid
      modify :task_id, :uuid
    end

    drop table(:group_tasks, prefix: prefix())

    drop table(:task_groups, prefix: prefix())

    drop constraint(:groups, "groups_course_id_fkey")

    drop constraint(:groups, "groups_created_by_id_fkey")

    alter table(:groups, prefix: prefix()) do
      remove :created_by_id
      remove :course_id
      remove :updated_at
      remove :inserted_at
      remove :max_members
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:group_members, [:group_id, :student_id],
                     name: "group_members_unique_group_student_index"
                   )

    drop constraint(:group_members, "group_members_group_id_fkey")

    drop constraint(:group_members, "group_members_student_id_fkey")

    alter table(:group_members, prefix: prefix()) do
      modify :student_id, :uuid
      modify :group_id, :uuid
    end

    drop table(:groups, prefix: prefix())

    drop constraint(:major_competencies, "major_competencies_parent_id_fkey")

    drop constraint(:major_competencies, "major_competencies_major_id_fkey")

    drop table(:major_competencies, prefix: prefix())

    alter table(:majors, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :duration
      remove :degree_type
      remove :college
      remove :description
      remove :code
      remove :name
    end

    drop constraint(:curriculum_designs, "curriculum_designs_major_id_fkey")

    alter table(:curriculum_designs, prefix: prefix()) do
      modify :major_id, :uuid
    end

    drop constraint(:analysis_reports, "analysis_reports_major_id_fkey")

    alter table(:analysis_reports, prefix: prefix()) do
      modify :major_id, :uuid
    end

    drop table(:majors, prefix: prefix())

    drop table(:curriculum_designs, prefix: prefix())

    drop table(:group_members, prefix: prefix())

    drop table(:analysis_reports, prefix: prefix())
  end
end
