defmodule KgEdu.Repo.TenantMigrations.MicroMajorNewResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:micro_major_resources, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :path, :text, null: false
      add :size, :bigint, null: false
      add :file_type, :text, null: false
      add :description, :text
      add :source_file_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :micro_major_course_id,
          references(:micro_major_courses,
            column: :id,
            name: "micro_major_resources_micro_major_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :micro_major_chapter_id, :uuid
    end

    # Clean up any stale rows from the old join table that have null course_id
    execute "DELETE FROM #{prefix()}.micro_major_courses WHERE course_id IS NULL"

    alter table(:micro_major_courses, prefix: prefix()) do
      remove :course_type
      remove :semester
      remove :period
      remove :credit
      remove :course_id
    end

    # Add title with default using raw SQL to avoid null check issue
    execute """
      ALTER TABLE #{prefix()}.micro_major_courses
      ADD COLUMN title text NOT NULL DEFAULT ''
    """

    alter table(:micro_major_courses, prefix: prefix()) do
      add :cover_url, :text
      add :teacher_id, :uuid
      add :status, :text, null: false, default: "draft"
      add :source_course_id, :uuid
    end

    # Now delete stale rows (title column exists)
    execute "DELETE FROM #{prefix()}.micro_major_courses WHERE course_id IS NULL"

    create table(:micro_major_videos, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :asset_id, :text, null: false
      add :playback_id, :text, null: false
      add :duration, :float
      add :thumbnail, :text
      add :source_video_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :micro_major_course_id,
          references(:micro_major_courses,
            column: :id,
            name: "micro_major_videos_micro_major_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :micro_major_chapter_id, :uuid
    end

    create table(:micro_major_chapters, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:micro_major_resources, prefix: prefix()) do
      modify :micro_major_chapter_id,
             references(:micro_major_chapters,
               column: :id,
               name: "micro_major_resources_micro_major_chapter_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :nilify_all
             )
    end

    alter table(:micro_major_videos, prefix: prefix()) do
      modify :micro_major_chapter_id,
             references(:micro_major_chapters,
               column: :id,
               name: "micro_major_videos_micro_major_chapter_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :nilify_all
             )
    end

    alter table(:micro_major_chapters, prefix: prefix()) do
      add :title, :text, null: false
      add :description, :text
      add :sort_order, :bigint, default: 0
      add :path, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :micro_major_course_id,
          references(:micro_major_courses,
            column: :id,
            name: "micro_major_chapters_micro_major_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :parent_chapter_id,
          references(:micro_major_chapters,
            column: :id,
            name: "micro_major_chapters_parent_chapter_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )
    end

    create table(:micro_major_exercises, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :question_content, :text, null: false
      add :answer, :text, null: false
      add :question_type, :text, null: false
      add :options, :map
      add :difficulty, :bigint
      add :position, :bigint
      add :answer_explanation, :text
      add :source_exercise_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :micro_major_course_id,
          references(:micro_major_courses,
            column: :id,
            name: "micro_major_exercises_micro_major_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :micro_major_chapter_id,
          references(:micro_major_chapters,
            column: :id,
            name: "micro_major_exercises_micro_major_chapter_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:micro_major_exercises, "micro_major_exercises_micro_major_course_id_fkey")

    drop constraint(:micro_major_exercises, "micro_major_exercises_micro_major_chapter_id_fkey")

    drop table(:micro_major_exercises, prefix: prefix())

    drop constraint(:micro_major_chapters, "micro_major_chapters_micro_major_course_id_fkey")

    drop constraint(:micro_major_chapters, "micro_major_chapters_parent_chapter_id_fkey")

    alter table(:micro_major_chapters, prefix: prefix()) do
      remove :parent_chapter_id
      remove :micro_major_course_id
      remove :updated_at
      remove :inserted_at
      remove :path
      remove :sort_order
      remove :description
      remove :title
    end

    drop constraint(:micro_major_videos, "micro_major_videos_micro_major_chapter_id_fkey")

    alter table(:micro_major_videos, prefix: prefix()) do
      modify :micro_major_chapter_id, :uuid
    end

    drop constraint(:micro_major_resources, "micro_major_resources_micro_major_chapter_id_fkey")

    alter table(:micro_major_resources, prefix: prefix()) do
      modify :micro_major_chapter_id, :uuid
    end

    drop table(:micro_major_chapters, prefix: prefix())

    drop constraint(:micro_major_videos, "micro_major_videos_micro_major_course_id_fkey")

    drop table(:micro_major_videos, prefix: prefix())

    create unique_index(:micro_major_courses, [:micro_major_id, :course_id],
             name: "micro_major_courses_unique"
           )

    alter table(:micro_major_courses, prefix: prefix()) do
      remove :source_course_id
      remove :status
      remove :teacher_id
      remove :cover_url
      remove :title

      add :course_id,
          references(:courses,
            column: :id,
            name: "micro_major_courses_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :credit, :float
      add :period, :bigint
      add :semester, :text
      add :course_type, :text, null: false, default: "required"
    end

    drop constraint(:micro_major_resources, "micro_major_resources_micro_major_course_id_fkey")

    drop table(:micro_major_resources, prefix: prefix())
  end
end
