defmodule KgEdu.Repo.TenantMigrations.AddRecommendationSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:student_knowledge_masteries, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mastery_level, :float, null: false, default: 0.0
      add :correct_count, :bigint, null: false, default: 0
      add :wrong_count, :bigint, null: false, default: 0
      add :practice_count, :bigint, null: false, default: 0
      add :last_practiced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :student_id,
          references(:users,
            column: :id,
            name: "student_knowledge_masteries_student_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "student_knowledge_masteries_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:learning_recommendations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :recommendation_type, :text, null: false
      add :priority, :bigint, null: false, default: 5
      add :reason, :text
      add :status, :text, null: false, default: "pending"
      add :viewed_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :dismissed_at, :utc_datetime
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :student_id,
          references(:users,
            column: :id,
            name: "learning_recommendations_student_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "learning_recommendations_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:learning_recommendations, "learning_recommendations_student_id_fkey")

    drop constraint(
           :learning_recommendations,
           "learning_recommendations_knowledge_resource_id_fkey"
         )

    drop table(:learning_recommendations, prefix: prefix())

    drop constraint(:student_knowledge_masteries, "student_knowledge_masteries_student_id_fkey")

    drop constraint(
           :student_knowledge_masteries,
           "student_knowledge_masteries_knowledge_resource_id_fkey"
         )

    drop table(:student_knowledge_masteries, prefix: prefix())
  end
end
