defmodule KgEdu.Repo.TenantMigrations.New8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_questions, prefix: prefix()) do
      add :difficulty, :bigint, default: 1
    end
  end

  def down do
    alter table(:knowledge_questions, prefix: prefix()) do
      remove :difficulty
    end
  end
end
