defmodule KgEdu.Repo.TenantMigrations.RemoveClassNameFromUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: prefix()) do
      remove :class_name
    end
  end

  def down do
    alter table(:users, prefix: prefix()) do
      add :class_name, :text
    end
  end
end
