defmodule KgEdu.Repo.TenantMigrations.AddCaseRelationNameToUserCase do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_cases, prefix: prefix()) do
      add :case_relation_name, :text
    end
  end

  def down do
    alter table(:user_cases, prefix: prefix()) do
      remove :case_relation_name
    end
  end
end
