defmodule KgEdu.Repo.TenantMigrations.AddEducationLevel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses, prefix: prefix()) do
      add :education_level, :text, default: "undergraduate"
    end
  end

  def down do
    alter table(:courses, prefix: prefix()) do
      remove :education_level
    end
  end
end
