defmodule KgEdu.Repo.TenantMigrations.AddCascadeDeleteToQuestionConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(
           :knowledge_question_connections,
           "knowledge_question_connections_target_question_id_fkey"
         )

    drop constraint(
           :knowledge_question_connections,
           "knowledge_question_connections_source_question_id_fkey"
         )

    alter table(:knowledge_question_connections, prefix: prefix()) do
      modify :source_question_id,
             references(:knowledge_questions,
               column: :id,
               name: "knowledge_question_connections_source_question_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :target_question_id,
             references(:knowledge_questions,
               column: :id,
               name: "knowledge_question_connections_target_question_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(
           :knowledge_question_connections,
           "knowledge_question_connections_source_question_id_fkey"
         )

    drop constraint(
           :knowledge_question_connections,
           "knowledge_question_connections_target_question_id_fkey"
         )

    alter table(:knowledge_question_connections, prefix: prefix()) do
      modify :target_question_id,
             references(:knowledge_questions,
               column: :id,
               name: "knowledge_question_connections_target_question_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :source_question_id,
             references(:knowledge_questions,
               column: :id,
               name: "knowledge_question_connections_source_question_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end
  end
end
