defmodule KgEdu.Repo.TenantMigrations.AddPositionToHomeworks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:homeworks, prefix: prefix()) do
      add :position, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:homeworks, prefix: prefix()) do
      remove :position
    end
  end
end
