defmodule KgEdu.Repo.TenantMigrations.AddParentMessageToEmails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:email_messages, prefix: prefix()) do
      add :parent_message_id,
          references(:email_messages,
            column: :id,
            name: "email_messages_parent_message_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:email_messages, "email_messages_parent_message_id_fkey")

    alter table(:email_messages, prefix: prefix()) do
      remove :parent_message_id
    end
  end
end
