defmodule KgEdu.Repo.TenantMigrations.AttendanceResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:check_in_sessions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :token, :text, null: false
      add :status, :text, null: false, default: "active"

      add :started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ended_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id,
          references(:users,
            column: :id,
            name: "check_in_sessions_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:check_in_records, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :checked_in_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "check_in_records_user_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :check_in_session_id,
          references(:check_in_sessions,
            column: :id,
            name: "check_in_records_check_in_session_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:check_in_records, "check_in_records_user_id_fkey")

    drop constraint(:check_in_records, "check_in_records_check_in_session_id_fkey")

    drop table(:check_in_records, prefix: prefix())

    drop constraint(:check_in_sessions, "check_in_sessions_created_by_id_fkey")

    drop table(:check_in_sessions, prefix: prefix())
  end
end
