defmodule KgEdu.Repo.TenantMigrations.TotalScore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:exams, prefix: prefix()) do
      remove :total_score
    end
  end

  def down do
    alter table(:exams, prefix: prefix()) do
      add :total_score, :bigint, null: false, default: 0
    end
  end
end
