defmodule KgEdu.Repo.TenantMigrations.AddEpxr do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:experiments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :experiment_type, :text, null: false, default: "online"
      add :duration_hours, :bigint
      add :difficulty_level, :text, null: false, default: "medium"
      add :objectives, :text
      add :requirements, :text
      add :equipment, :text
      add :status, :text, null: false, default: "draft"
      add :sort_order, :bigint, default: 1
      add :guide_url, :text
      add :guide_title, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "experiments_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :chapter_id,
          references(:chapters,
            column: :id,
            name: "experiments_chapter_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :nilify_all
          )

      add :created_by_id,
          references(:users,
            column: :id,
            name: "experiments_created_by_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :nilify_all
          )
    end

    create table(:experiment_knowledge_resources, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :experiment_id,
          references(:experiments,
            column: :id,
            name: "experiment_knowledge_resources_experiment_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "experiment_knowledge_resources_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:experiment_abilities, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ability_type, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :experiment_id,
          references(:experiments,
            column: :id,
            name: "experiment_abilities_experiment_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :main_ability_id,
          references(:main_abilities,
            column: :id,
            name: "experiment_abilities_main_ability_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )

      add :sub_ability_id,
          references(:sub_abilities,
            column: :id,
            name: "experiment_abilities_sub_ability_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:experiment_abilities, "experiment_abilities_experiment_id_fkey")

    drop constraint(:experiment_abilities, "experiment_abilities_main_ability_id_fkey")

    drop constraint(:experiment_abilities, "experiment_abilities_sub_ability_id_fkey")

    drop table(:experiment_abilities, prefix: prefix())

    drop constraint(
           :experiment_knowledge_resources,
           "experiment_knowledge_resources_experiment_id_fkey"
         )

    drop constraint(
           :experiment_knowledge_resources,
           "experiment_knowledge_resources_knowledge_resource_id_fkey"
         )

    drop table(:experiment_knowledge_resources, prefix: prefix())

    drop constraint(:experiments, "experiments_course_id_fkey")

    drop constraint(:experiments, "experiments_chapter_id_fkey")

    drop constraint(:experiments, "experiments_created_by_id_fkey")

    drop table(:experiments, prefix: prefix())
  end
end
