defmodule KgEdu.Repo.TenantMigrations.AddEmailResources do
  @moduledoc """
  Adds email_configs and email_messages tables.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:email_configs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email_address, :text, null: false
      add :sender_name, :text, null: false
      add :api_key, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "email_configs_user_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:email_messages, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject, :text, null: false
      add :body, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
      add :sent_at, :utc_datetime
      add :failed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sender_user_id,
          references(:users,
            column: :id,
            name: "email_messages_sender_user_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :receiver_user_id,
          references(:users,
            column: :id,
            name: "email_messages_receiver_user_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:email_messages, "email_messages_sender_user_id_fkey")

    drop constraint(:email_messages, "email_messages_receiver_user_id_fkey")

    drop table(:email_messages, prefix: prefix())

    drop constraint(:email_configs, "email_configs_user_id_fkey")

    drop table(:email_configs, prefix: prefix())
  end
end
