defmodule KgEdu.Repo.TenantMigrations.AddAiConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:micro_major_enrollments, prefix: prefix()) do
      add :reviewed_by_id, :uuid
      add :rejected_reason, :text
      add :reviewed_at, :utc_datetime
    end
  end

  def down do
    alter table(:micro_major_enrollments, prefix: prefix()) do
      remove :reviewed_at
      remove :rejected_reason
      remove :reviewed_by_id
    end
  end
end
