defmodule KgEdu.Repo.TenantMigrations.AddAbilityResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sub_ability_knowledge_resources, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sub_ability_id, :uuid, null: false
      add :knowledge_resource_id, :uuid, null: false
    end

    create table(:sub_abilities, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sub_ability_knowledge_resources, prefix: prefix()) do
      modify :sub_ability_id,
             references(:sub_abilities,
               column: :id,
               name: "sub_ability_knowledge_resources_sub_ability_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "sub_ability_knowledge_resources_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:sub_abilities, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :main_ability_id, :uuid, null: false
    end

    create table(:main_abilities, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sub_abilities, prefix: prefix()) do
      modify :main_ability_id,
             references(:main_abilities,
               column: :id,
               name: "sub_abilities_main_ability_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:main_abilities, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "main_abilities_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:main_abilities, "main_abilities_course_id_fkey")

    alter table(:main_abilities, prefix: prefix()) do
      remove :course_id
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:sub_abilities, "sub_abilities_main_ability_id_fkey")

    alter table(:sub_abilities, prefix: prefix()) do
      modify :main_ability_id, :uuid
    end

    drop table(:main_abilities, prefix: prefix())

    alter table(:sub_abilities, prefix: prefix()) do
      remove :main_ability_id
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(
           :sub_ability_knowledge_resources,
           "sub_ability_knowledge_resources_sub_ability_id_fkey"
         )

    drop constraint(
           :sub_ability_knowledge_resources,
           "sub_ability_knowledge_resources_knowledge_resource_id_fkey"
         )

    alter table(:sub_ability_knowledge_resources, prefix: prefix()) do
      modify :knowledge_resource_id, :uuid
      modify :sub_ability_id, :uuid
    end

    drop table(:sub_abilities, prefix: prefix())

    drop table(:sub_ability_knowledge_resources, prefix: prefix())
  end
end
