defmodule KgEdu.Repo.TenantMigrations.ExerciseImportFix do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:micro_major_exercises, prefix: prefix()) do
      modify :answer, :text, null: true
    end
  end

  def down do
    alter table(:micro_major_exercises, prefix: prefix()) do
      modify :answer, :text, null: false
    end
  end
end
