defmodule KgEdu.Repo.TenantMigrations.AddDiscussionRatingAndSessionId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:discussions, prefix: prefix()) do
      add :rating, :bigint, default: 5
    end
  end

  def down do
    alter table(:discussions, prefix: prefix()) do
      remove :rating
    end
  end
end
