defmodule KgEdu.Repo.TenantMigrations.AddBrowseCountToCourse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses, prefix: prefix()) do
      add :browse_count, :bigint, default: 0
    end
  end

  def down do
    alter table(:courses, prefix: prefix()) do
      remove :browse_count
    end
  end
end
