defmodule KgEdu.Repo.TenantMigrations.AddAbilityRelations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ability_relations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_type, :text, null: false
      add :source_id, :uuid, null: false
      add :target_type, :text, null: false
      add :target_id, :uuid, null: false
      add :course_id, :uuid, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ability_relations, [:source_type, :source_id, :target_type, :target_id],
             name: "ability_relations_unique_ability_relation_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :ability_relations,
                     [:source_type, :source_id, :target_type, :target_id],
                     name: "ability_relations_unique_ability_relation_index"
                   )

    drop table(:ability_relations, prefix: prefix())
  end
end
