defmodule KgEdu.Repo.TenantMigrations.AddParentKnowledgeResourceId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_resources, prefix: prefix()) do
      add :parent_knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "knowledge_resources_parent_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:knowledge_resources, "knowledge_resources_parent_knowledge_resource_id_fkey")

    alter table(:knowledge_resources, prefix: prefix()) do
      remove :parent_knowledge_resource_id
    end
  end
end
