defmodule KgEdu.Repo.TenantMigrations.ExtendActivityLogMm do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:activity_logs, prefix: prefix()) do
      add :micro_major_course_id, :uuid
      add :micro_major_course_title, :text
      add :micro_major_id, :uuid
      add :micro_major_name, :text
    end
  end

  def down do
    alter table(:activity_logs, prefix: prefix()) do
      remove :micro_major_name
      remove :micro_major_id
      remove :micro_major_course_title
      remove :micro_major_course_id
    end
  end
end
