defmodule KgEdu.Repo.TenantMigrations.AddDigitalHumanTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:digital_human_tasks, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :status, :text, null: false, default: "queued"
      add :progress_message, :text
      add :image_url, :text
      add :audio_url, :text
      add :video_url, :text
      add :dashscope_task_id, :text
      add :resolution, :text, default: "480P"
      add :error_message, :text
      add :created_by_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:digital_human_tasks, prefix: prefix())
  end
end
