defmodule KgEdu.Repo.TenantMigrations.AddCascadeDeleteToKnowledgeRelatedResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:knowledge_questions, "knowledge_questions_knowledge_resource_id_fkey")

    alter table(:knowledge_questions, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_questions_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    drop constraint(:user_cases, "user_cases_knowledge_resource_id_fkey")

    alter table(:user_cases, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "user_cases_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    drop constraint(:homeworks, "homeworks_knowledge_resource_id_fkey")

    alter table(:homeworks, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "homeworks_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    drop constraint(:videos, "videos_knowledge_resource_id_fkey")

    alter table(:videos, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "videos_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    drop constraint(:knowledge_relations, "knowledge_relations_target_knowledge_id_fkey")

    drop constraint(:knowledge_relations, "knowledge_relations_source_knowledge_id_fkey")

    alter table(:knowledge_relations, prefix: prefix()) do
      modify :source_knowledge_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_relations_source_knowledge_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :target_knowledge_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_relations_target_knowledge_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    drop constraint(:files, "files_knowledge_resource_id_fkey")

    alter table(:files, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "files_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:files, "files_knowledge_resource_id_fkey")

    alter table(:files, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "files_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    drop constraint(:knowledge_relations, "knowledge_relations_source_knowledge_id_fkey")

    drop constraint(:knowledge_relations, "knowledge_relations_target_knowledge_id_fkey")

    alter table(:knowledge_relations, prefix: prefix()) do
      modify :target_knowledge_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_relations_target_knowledge_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :source_knowledge_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_relations_source_knowledge_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    drop constraint(:videos, "videos_knowledge_resource_id_fkey")

    alter table(:videos, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "videos_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    drop constraint(:homeworks, "homeworks_knowledge_resource_id_fkey")

    alter table(:homeworks, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "homeworks_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    drop constraint(:user_cases, "user_cases_knowledge_resource_id_fkey")

    alter table(:user_cases, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "user_cases_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    drop constraint(:knowledge_questions, "knowledge_questions_knowledge_resource_id_fkey")

    alter table(:knowledge_questions, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "knowledge_questions_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end
  end
end
