defmodule KgEdu.Repo.TenantMigrations.JobCompetencyGraphs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ability_knowledge_links, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ability_id, :uuid, null: false
      add :knowledge_resource_id, :uuid, null: false
      add :graph_id, :uuid, null: false
      add :support_level, :text, null: false, default: "primary"
      add :weight, :float, null: false, default: 1.0
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:job_task_abilities, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ability_knowledge_links, prefix: prefix()) do
      modify :ability_id,
             references(:job_task_abilities,
               column: :id,
               name: "ability_knowledge_links_ability_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "ability_knowledge_links_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    alter table(:job_task_abilities, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text
      add :level, :text
      add :weight, :float, null: false, default: 1.0
      add :sort_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :core_task_id, :uuid, null: false
      add :graph_id, :uuid, null: false
    end

    create table(:job_competency_graphs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ability_knowledge_links, prefix: prefix()) do
      modify :graph_id,
             references(:job_competency_graphs,
               column: :id,
               name: "ability_knowledge_links_graph_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    create unique_index(:ability_knowledge_links, [:ability_id, :knowledge_resource_id],
             name: "ability_knowledge_links_unique"
           )

    alter table(:job_competency_graphs, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text
      add :is_active, :boolean, null: false, default: true
      add :version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :job_position_id,
          references(:job_positions,
            column: :id,
            name: "job_competency_graphs_job_position_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:job_core_tasks, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:job_task_abilities, prefix: prefix()) do
      modify :core_task_id,
             references(:job_core_tasks,
               column: :id,
               name: "job_task_abilities_core_task_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :graph_id,
             references(:job_competency_graphs,
               column: :id,
               name: "job_task_abilities_graph_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    alter table(:job_core_tasks, prefix: prefix()) do
      add :title, :text, null: false
      add :description, :text
      add :weight, :float, null: false, default: 1.0
      add :sort_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :graph_id,
          references(:job_competency_graphs,
            column: :id,
            name: "job_core_tasks_graph_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :job_position_id,
          references(:job_positions,
            column: :id,
            name: "job_core_tasks_job_position_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:job_core_tasks, "job_core_tasks_graph_id_fkey")

    drop constraint(:job_core_tasks, "job_core_tasks_job_position_id_fkey")

    alter table(:job_core_tasks, prefix: prefix()) do
      remove :job_position_id
      remove :graph_id
      remove :updated_at
      remove :inserted_at
      remove :sort_order
      remove :weight
      remove :description
      remove :title
    end

    drop constraint(:job_task_abilities, "job_task_abilities_core_task_id_fkey")

    drop constraint(:job_task_abilities, "job_task_abilities_graph_id_fkey")

    alter table(:job_task_abilities, prefix: prefix()) do
      modify :graph_id, :uuid
      modify :core_task_id, :uuid
    end

    drop table(:job_core_tasks, prefix: prefix())

    drop constraint(:job_competency_graphs, "job_competency_graphs_job_position_id_fkey")

    alter table(:job_competency_graphs, prefix: prefix()) do
      remove :job_position_id
      remove :updated_at
      remove :inserted_at
      remove :version
      remove :is_active
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:ability_knowledge_links, [:ability_id, :knowledge_resource_id],
                     name: "ability_knowledge_links_unique"
                   )

    drop constraint(:ability_knowledge_links, "ability_knowledge_links_graph_id_fkey")

    alter table(:ability_knowledge_links, prefix: prefix()) do
      modify :graph_id, :uuid
    end

    drop table(:job_competency_graphs, prefix: prefix())

    alter table(:job_task_abilities, prefix: prefix()) do
      remove :graph_id
      remove :core_task_id
      remove :updated_at
      remove :inserted_at
      remove :sort_order
      remove :weight
      remove :level
      remove :description
      remove :name
    end

    drop constraint(:ability_knowledge_links, "ability_knowledge_links_ability_id_fkey")

    drop constraint(
           :ability_knowledge_links,
           "ability_knowledge_links_knowledge_resource_id_fkey"
         )

    alter table(:ability_knowledge_links, prefix: prefix()) do
      modify :knowledge_resource_id, :uuid
      modify :ability_id, :uuid
    end

    drop table(:job_task_abilities, prefix: prefix())

    drop table(:ability_knowledge_links, prefix: prefix())
  end
end
