defmodule KgEdu.Repo.TenantMigrations.AddSubAbilityKnowledgeIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(
             :sub_ability_knowledge_resources,
             [:sub_ability_id, :knowledge_resource_id],
             name: "sub_ability_knowledge_resources_unique_sub_ability_knowledge_resource_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :sub_ability_knowledge_resources,
                     [:sub_ability_id, :knowledge_resource_id],
                     name:
                       "sub_ability_knowledge_resources_unique_sub_ability_knowledge_resource_index"
                   )
  end
end
