defmodule KgEdu.Repo.TenantMigrations.AddExamResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:student_exams, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "in_progress"
      add :score, :bigint, null: false, default: 0
      add :passed, :boolean, null: false, default: false
      add :started_at, :utc_datetime
      add :submitted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :exam_id, :uuid, null: false
      add :student_id, :uuid, null: false
    end

    create table(:student_exam_answers, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :answer, :text
      add :points_earned, :bigint, null: false, default: 0
      add :graded, :boolean, null: false, default: false
      add :feedback, :text
      add :answered_at, :utc_datetime
      add :graded_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :student_exam_id,
          references(:student_exams,
            column: :id,
            name: "student_exam_answers_student_exam_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :exam_exercise_id, :uuid, null: false
      add :exercise_id, :uuid, null: false
    end

    create table(:exams, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:student_exams, prefix: prefix()) do
      modify :exam_id,
             references(:exams,
               column: :id,
               name: "student_exams_exam_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :student_id,
             references(:users,
               column: :id,
               name: "student_exams_student_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :nilify_all
             )
    end

    alter table(:exams, prefix: prefix()) do
      add :title, :text, null: false
      add :description, :text
      add :exam_type, :text, null: false, default: "quiz"
      add :exam_date, :utc_datetime
      add :duration_minutes, :bigint, null: false, default: 60
      add :total_score, :bigint, null: false, default: 0
      add :passing_score, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "exams_course_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )

      add :created_by_id,
          references(:users,
            column: :id,
            name: "exams_created_by_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :nilify_all
          ),
          null: false
    end

    create table(:exam_exercises, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:student_exam_answers, prefix: prefix()) do
      modify :exam_exercise_id,
             references(:exam_exercises,
               column: :id,
               name: "student_exam_answers_exam_exercise_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )

      modify :exercise_id,
             references(:exercises,
               column: :id,
               name: "student_exam_answers_exercise_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    alter table(:exam_exercises, prefix: prefix()) do
      add :points, :bigint, null: false, default: 1
      add :order, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :exam_id,
          references(:exams,
            column: :id,
            name: "exam_exercises_exam_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :exercise_id,
          references(:exercises,
            column: :id,
            name: "exam_exercises_exercise_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:exam_exercises, "exam_exercises_exam_id_fkey")

    drop constraint(:exam_exercises, "exam_exercises_exercise_id_fkey")

    alter table(:exam_exercises, prefix: prefix()) do
      remove :exercise_id
      remove :exam_id
      remove :updated_at
      remove :inserted_at
      remove :order
      remove :points
    end

    drop constraint(:student_exam_answers, "student_exam_answers_exam_exercise_id_fkey")

    drop constraint(:student_exam_answers, "student_exam_answers_exercise_id_fkey")

    alter table(:student_exam_answers, prefix: prefix()) do
      modify :exercise_id, :uuid
      modify :exam_exercise_id, :uuid
    end

    drop table(:exam_exercises, prefix: prefix())

    drop constraint(:exams, "exams_course_id_fkey")

    drop constraint(:exams, "exams_created_by_id_fkey")

    alter table(:exams, prefix: prefix()) do
      remove :created_by_id
      remove :course_id
      remove :updated_at
      remove :inserted_at
      remove :passing_score
      remove :total_score
      remove :duration_minutes
      remove :exam_date
      remove :exam_type
      remove :description
      remove :title
    end

    drop constraint(:student_exams, "student_exams_exam_id_fkey")

    drop constraint(:student_exams, "student_exams_student_id_fkey")

    alter table(:student_exams, prefix: prefix()) do
      modify :student_id, :uuid
      modify :exam_id, :uuid
    end

    drop table(:exams, prefix: prefix())

    drop constraint(:student_exam_answers, "student_exam_answers_student_exam_id_fkey")

    drop table(:student_exam_answers, prefix: prefix())

    drop table(:student_exams, prefix: prefix())
  end
end
