defmodule KgEdu.Repo.TenantMigrations.EmailMessage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:email_messages, prefix: prefix()) do
      add :read_status, :text, null: false, default: "unread"
      add :read_at, :utc_datetime
    end
  end

  def down do
    alter table(:email_messages, prefix: prefix()) do
      remove :read_at
      remove :read_status
    end
  end
end
