defmodule :"Elixir.KgEdu.Repo.TenantMigrations.Delete-all-courses" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:links, "links_knowledge_resource_id_fkey")

    alter table(:links, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "links_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    drop constraint(
           :sub_ability_knowledge_resources,
           "sub_ability_knowledge_resources_knowledge_resource_id_fkey"
         )

    alter table(:sub_ability_knowledge_resources, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "sub_ability_knowledge_resources_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(
           :sub_ability_knowledge_resources,
           "sub_ability_knowledge_resources_knowledge_resource_id_fkey"
         )

    alter table(:sub_ability_knowledge_resources, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "sub_ability_knowledge_resources_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    drop constraint(:links, "links_knowledge_resource_id_fkey")

    alter table(:links, prefix: prefix()) do
      modify :knowledge_resource_id,
             references(:knowledge_resources,
               column: :id,
               name: "links_knowledge_resource_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end
  end
end
