defmodule KgEdu.Repo.TenantMigrations.AddCertNoFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:micro_major_certificate_templates, prefix: prefix()) do
      add :background_image_url, :text
      add :name_field_x, :decimal, default: "0.2"
      add :name_field_y, :decimal, default: "0.45"
      add :name_field_width, :decimal, default: "0.6"
      add :name_field_height, :decimal, default: "0.08"
      add :name_font_family, :text, default: "serif"
      add :name_font_size, :bigint, default: 36
      add :name_font_weight, :text, default: "normal"
      add :name_color, :text, default: "#000000"
      add :name_letter_spacing, :bigint, default: 4
      add :name_text_align, :text, default: "center"
      add :cert_no_field_x, :decimal, default: "0.2"
      add :cert_no_field_y, :decimal, default: "0.55"
      add :cert_no_field_width, :decimal, default: "0.6"
      add :cert_no_field_height, :decimal, default: "0.06"
      add :cert_no_font_family, :text, default: "serif"
      add :cert_no_font_size, :bigint, default: 24
      add :cert_no_font_weight, :text, default: "normal"
      add :cert_no_color, :text, default: "#000000"
      add :cert_no_letter_spacing, :bigint, default: 2
      add :cert_no_text_align, :text, default: "center"
    end

    create unique_index(:micro_major_certificate_templates, [:micro_major_id],
             name: "micro_major_certificate_templates_unique_micro_major_template_index"
           )

    alter table(:sub_ability_knowledge_resources, prefix: prefix()) do
      add :support_level, :text, null: false, default: "primary"
      add :weight, :float, null: false, default: 1.0
      add :description, :text
    end
  end

  def down do
    alter table(:sub_ability_knowledge_resources, prefix: prefix()) do
      remove :description
      remove :weight
      remove :support_level
    end

    drop_if_exists unique_index(:micro_major_certificate_templates, [:micro_major_id],
                     name: "micro_major_certificate_templates_unique_micro_major_template_index"
                   )

    alter table(:micro_major_certificate_templates, prefix: prefix()) do
      remove :cert_no_text_align
      remove :cert_no_letter_spacing
      remove :cert_no_color
      remove :cert_no_font_weight
      remove :cert_no_font_size
      remove :cert_no_font_family
      remove :cert_no_field_height
      remove :cert_no_field_width
      remove :cert_no_field_y
      remove :cert_no_field_x
      remove :name_text_align
      remove :name_letter_spacing
      remove :name_color
      remove :name_font_weight
      remove :name_font_size
      remove :name_font_family
      remove :name_field_height
      remove :name_field_width
      remove :name_field_y
      remove :name_field_x
      remove :background_image_url
    end
  end
end
