defmodule KgEdu.Repo.TenantMigrations.AddEnNameToResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_resources, prefix: prefix()) do
      add :en_name, :text
    end
  end

  def down do
    alter table(:knowledge_resources, prefix: prefix()) do
      remove :en_name
    end
  end
end
