defmodule KgEdu.Repo.TenantMigrations.Answer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:exercises, prefix: prefix()) do
      add :answer_explanation, :text
    end
  end

  def down do
    alter table(:exercises, prefix: prefix()) do
      remove :answer_explanation
    end
  end
end
