defmodule KgEdu.Repo.TenantMigrations.AddDiscussionRatingAndSessionId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    schema = prefix()

    execute """
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = '#{schema}'
            AND table_name = 'discussions'
            AND column_name = 'rating'
        ) THEN
          ALTER TABLE #{schema}.discussions ADD COLUMN rating bigint DEFAULT 5;
        END IF;
      END $$;
    """
  end

  def down do
    schema = prefix()

    execute """
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = '#{schema}'
            AND table_name = 'discussions'
            AND column_name = 'rating'
        ) THEN
          ALTER TABLE #{schema}.discussions DROP COLUMN rating;
        END IF;
      END $$;
    """
  end
end
