defmodule KgEdu.Repo.TenantMigrations.AddUserCaseResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_cases, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :content, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :knowledge_resource_id,
          references(:knowledge_resources,
            column: :id,
            name: "user_cases_knowledge_resource_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:user_cases, "user_cases_knowledge_resource_id_fkey")

    drop table(:user_cases, prefix: prefix())
  end
end
