defmodule KgEdu.Repo.TenantMigrations.AddDimensionToKnowledgeResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_resources, prefix: prefix()) do
      add :dimension, :text
    end
  end

  def down do
    alter table(:knowledge_resources, prefix: prefix()) do
      remove :dimension
    end
  end
end
