defmodule KgEdu.Repo.TenantMigrations.ChangeCameraScriptsScenesType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:camera_scripts, prefix: prefix()) do
      modify :scenes, :jsonb
    end
  end

  def down do
    alter table(:camera_scripts, prefix: prefix()) do
      modify :scenes, :map
    end
  end
end
