defmodule KgEdu.Repo.TenantMigrations.AddCertificateTemplatesAndCertificates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:micro_major_certificates, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :micro_major_id,
          references(:micro_majors,
            column: :id,
            name: "micro_major_certificates_micro_major_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :student_id,
          references(:users,
            column: :id,
            name: "micro_major_certificates_student_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :enrollment_id,
          references(:micro_major_enrollments,
            column: :id,
            name: "micro_major_certificates_enrollment_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )

      add :template_id, :uuid
      add :certificate_type, :text, null: false, default: "generated_pdf"
      add :file_url, :text
      add :file_name, :text
      add :cert_no, :text
      add :issue_date, :utc_datetime
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:micro_major_certificate_templates, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:micro_major_certificates, prefix: prefix()) do
      modify :template_id,
             references(:micro_major_certificate_templates,
               column: :id,
               name: "micro_major_certificates_template_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :nilify_all
             )
    end

    alter table(:micro_major_certificate_templates, prefix: prefix()) do
      add :micro_major_id,
          references(:micro_majors,
            column: :id,
            name: "micro_major_certificate_templates_micro_major_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          ),
          null: false

      add :style, :text, null: false, default: "simple"
      add :issuer_name, :text
      add :extra_text, :text
      add :logo_url, :text
      add :seal_url, :text
      add :signature_url, :text
      add :title_color, :text, default: "#2b2b28"
      add :title_font, :text, default: "ui-sans-serif, system-ui, sans-serif"
      add :border_color, :text, default: "#8a8a86"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(
           :micro_major_certificate_templates,
           "micro_major_certificate_templates_micro_major_id_fkey"
         )

    alter table(:micro_major_certificate_templates, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :border_color
      remove :title_font
      remove :title_color
      remove :signature_url
      remove :seal_url
      remove :logo_url
      remove :extra_text
      remove :issuer_name
      remove :style
      remove :micro_major_id
    end

    drop constraint(:micro_major_certificates, "micro_major_certificates_template_id_fkey")

    alter table(:micro_major_certificates, prefix: prefix()) do
      modify :template_id, :uuid
    end

    drop table(:micro_major_certificate_templates, prefix: prefix())

    drop constraint(:micro_major_certificates, "micro_major_certificates_micro_major_id_fkey")

    drop constraint(:micro_major_certificates, "micro_major_certificates_student_id_fkey")

    drop constraint(:micro_major_certificates, "micro_major_certificates_enrollment_id_fkey")

    drop table(:micro_major_certificates, prefix: prefix())
  end
end
