defmodule KgEdu.Repo.TenantMigrations.AddChromaKeyRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chroma_key_records, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_image_url, :text, null: false
      add :result_image_url, :text
      add :color, :text, null: false, default: "green"
      add :similarity, :float, null: false, default: 0.4
      add :blend, :float, null: false, default: 0.1
      add :yuv, :boolean, null: false, default: true
      add :despill, :boolean, null: false, default: false
      add :created_by_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:chroma_key_records, prefix: prefix())
  end
end
