defmodule KgEdu.Repo.TenantMigrations.Add11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:files, prefix: prefix()) do
      add :source, :text
    end
  end

  def down do
    alter table(:files, prefix: prefix()) do
      remove :source
    end
  end
end
