defmodule KgEdu.Repo.TenantMigrations.AddDiscussionSession do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:discussion_sessions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :token, :text, null: false
      add :status, :text, null: false, default: "active"

      add :started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ended_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :course_id,
          references(:courses,
            column: :id,
            name: "discussion_sessions_course_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "discussion_sessions_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:discussion_sessions, "discussion_sessions_course_id_fkey")

    drop constraint(:discussion_sessions, "discussion_sessions_created_by_id_fkey")

    drop table(:discussion_sessions, prefix: prefix())
  end
end
