defmodule KgEdu.Repo.TenantMigrations.Add6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:exercises, prefix: prefix()) do
      add :position, :bigint
    end
  end

  def down do
    alter table(:exercises, prefix: prefix()) do
      remove :position
    end
  end
end
