defmodule KgEdu.Repo.TenantMigrations.AddChapterPath do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chapters, prefix: prefix()) do
      add :path, :text
    end
  end

  def down do
    alter table(:chapters, prefix: prefix()) do
      remove :path
    end
  end
end
