defmodule KgEdu.Repo.TenantMigrations.AddCreatedBy2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:knowledge_resources, prefix: prefix()) do
      add :sort_path, :text, default: ""
      add :display_order, :bigint
    end
  end

  def down do
    alter table(:knowledge_resources, prefix: prefix()) do
      remove :display_order
      remove :sort_path
    end
  end
end
